# V-STaR Benchmark Configuration
# For V-STaR dataset: https://github.com/V-STaR-Bench/V-STaR/

name: vstar
_target_: vstar_benchmark.VStarBenchmark

# Data directory
data_dir: /hkfs/work/workspace/scratch/uemjv-roboG_datasets/V-STaR  # /hkfs/work/workspace/scratch/ulqho-robot_datasets/datasets/benchmarks/V-STaR

# Optional: limit number of samples for quick testing
max_samples: 20

# Optional: select a different VQA scoring model for testing
# If left out, defaults to Qwen/Qwen2.5-72B-Instruct
vqa_score_model: Qwen/Qwen2.5-3B-Instruct